<a href="https://colab.research.google.com/github/JaeHeee/Pytorch_Tutorial/blob/main/code/What_is_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import torch

### Tensor

Tensor는 NumPy의 ndarray와 유사하며, GPU를 사용한 연산 가속도 가능합니다.

초기화되지 않은 5x3 행렬 생성

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[3.2977e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.1129e-35]])


무작위로 초기화된 행렬 생성

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7472, 0.7015, 0.3151],
        [0.9469, 0.5415, 0.4592],
        [0.6100, 0.7473, 0.9075],
        [0.3795, 0.0323, 0.2699],
        [0.2553, 0.7476, 0.0514]])


dtype이 long이고 0으로 채워진 행렬 생성

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 직접 생성

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


기존 tensor를 바탕으로 새로운 tensor를 생성. 이들 메소드(method)는 사용자로부터 새로운 값을 제공받지 않은 한, 입력 tensor의 속성들(e.g. dtype)을 재사용

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
# dtype을 override
# 결과는 동일한 크기
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.0857, 0.5868, 0.1076],
        [0.6086, 0.7671, 0.9627],
        [0.6494, 0.3762, 0.6607],
        [0.6540, 0.3319, 0.5362],
        [0.3955, 0.2511, 0.0933]])

행렬의 크기

In [ ]:
print(x.size())
# torch.Size는 tuple로, 모든 tuple 연산을 지원

torch.Size([5, 3])


### Operations

덧셈 - 1

In [ ]:
y = torch.rand(5, 3)
print(y)

tensor([[0.0553, 0.1098, 0.4258],
        [0.1175, 0.7579, 0.8009],
        [0.8073, 0.4464, 0.7548],
        [0.2055, 0.1834, 0.3515],
        [0.9077, 0.9543, 0.4420]])


In [ ]:
x

tensor([[0.0857, 0.5868, 0.1076],
        [0.6086, 0.7671, 0.9627],
        [0.6494, 0.3762, 0.6607],
        [0.6540, 0.3319, 0.5362],
        [0.3955, 0.2511, 0.0933]])

In [ ]:
print(x+y)

tensor([[0.1410, 0.6966, 0.5333],
        [0.7261, 1.5250, 1.7636],
        [1.4567, 0.8226, 1.4155],
        [0.8595, 0.5153, 0.8877],
        [1.3032, 1.2054, 0.5353]])


덧셈 - 2

In [ ]:
print(torch.add(x,y))

tensor([[0.1410, 0.6966, 0.5333],
        [0.7261, 1.5250, 1.7636],
        [1.4567, 0.8226, 1.4155],
        [0.8595, 0.5153, 0.8877],
        [1.3032, 1.2054, 0.5353]])


덧셈 - 결과 tensor를 인자로 제공

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.1410, 0.6966, 0.5333],
        [0.7261, 1.5250, 1.7636],
        [1.4567, 0.8226, 1.4155],
        [0.8595, 0.5153, 0.8877],
        [1.3032, 1.2054, 0.5353]])


덧셈 - in-place 방식

In [ ]:
# in-place 방식으로 tensor의 값을 변경하는 연산 뒤에는 _''가 붙음. e.g. ''x.copy_(y),x.t_()는 x를 변경
y.add_(x)
print(y)

tensor([[0.1410, 0.6966, 0.5333],
        [0.7261, 1.5250, 1.7636],
        [1.4567, 0.8226, 1.4155],
        [0.8595, 0.5153, 0.8877],
        [1.3032, 1.2054, 0.5353]])


NumPy스러운 인덱싱 표기 방법을 사용 가능

In [ ]:
print(x[:, 1])

tensor([0.5868, 0.7671, 0.3762, 0.3319, 0.2511])


크기 변경 : tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 `torch.view`를 사용

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


tensor에 하나의 값만 존재한다면, `.item()`을 사용하여 숫자 값을 얻을 수 있음

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.1679])
-2.1678531169891357


전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등, 100가지 이상의 [Tensor 연산](https://pytorch.org/docs/stable/torch.html)

### NumPy 변환 (Bridge)

(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경 가능

#### Torch Tensor를 NumPy 배열로 변환

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


NumPy 배열의 값이 어떻게 변하는지 확인

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### NumPy 배열을 Torch Tensor로 변환

np (NumPy) 배열을 변경하면 Torch Tensor의 값도 자동 변경됨

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로 변환할 수 있고, (NumPy에서 Tensor로의) 반대 변환도 가능

### CUDA Tensors

`.to` 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있음

In [ ]:
# ''torch.device'' 를 사용하여 tensor를 GPU 안팎으로 이동
if torch.cuda.is_available():
    device = torch.device("cuda") # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device) # GPU 상에 직접적으로 tensor를 생성
    x = x.to(device) # ''.to("cuda")''를 사용
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) # ''.to'' 는 dtype도 함께 변경

tensor([-1.1679], device='cuda:0')
tensor([-1.1679], dtype=torch.float64)
